Update terraform-template.yml

diff --git a/.azure/templates/terraform-template.yml b/.azure/templates/terraform-template.yml
--- a/.azure/templates/terraform-template.yml
+++ b/.azure/templates/terraform-template.yml
@@ -8,13 +8,20 @@ jobs:
   - job: TerraformJob
     displayName: "Terraform ${{ parameters.action }} (${{ parameters.environment }})"
     pool:
-      name: aws-agent
+      name: aws_host
     steps:
       - checkout: self
 
+      # Check if tflint is installed, install only if missing
       - script: |
-          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
-        displayName: "Install tflint"
+          if ! command -v tflint &> /dev/null; then
+            echo "tflint not found, installing..."
+            curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
+          else
+            echo "tflint already installed."
+            tflint --version
+          fi
+        displayName: "Ensure tflint is installed"
 
       - ${{ if eq(parameters.action, 'fmt') }}:
           - script: |
